name: dad_mocu_kuramoto
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - numpy
  - matplotlib
  - scipy
  - pyyaml
  - pip
  - pip:
    - torch>=2.0.0
    - numpy>=1.24.0
    - matplotlib>=3.5.0
    - scipy>=1.9.0
    - PyYAML>=6.0.0
