# Fast config with paper-matched approach but fewer samples

N: 5
K: 4
seed: 42

prior_lower: 0.05
prior_upper: 0.50

omega:
  kind: "uniform"
  low: -3.0
  high: 3.0

sim:
  dt: 0.00625   # 1/160
  T: 3.0
  burn_in: 1.0
  R_target: 0.95
  method: "RK45"
  n_trajectories: 2

surrogate:
  hidden: 128
  dropout: 0.1
  mocu_scale: 1.0
  
  n_train: 500
  n_val: 100
  n_theta_samples: 100   # Reduced from 1000 for speed, but still reasonable
  
  epochs: 50
  lr: 0.001
  batch_size: 512
  
  n_erm_samples: 5
  max_erm_candidates: 8

dad_rl:
  hidden: 128
  epochs: 20
  episodes_per_epoch: 30
  lr: 0.0003
  
  n_train: 100
  n_val: 20

enable_dad: true

advanced:
  bisection:
    tol: 0.002
    max_expand: 15
    max_iter: 30
    verbose: false
  data_gen:
    parallel: false
    cache_labels: true
    two_stage: true
    use_adaptive_bounds: true
  eval:
    save_trajectories: false
    compute_diagnostics: true