# Updated configs/config.yaml
# RTX 4090 Optimized Configuration with Two-Stage Data Generation

N: 5                    # Number of oscillators
K: 4                    # Number of experiments
seed: 42

prior_lower: 0.05
prior_upper: 0.50

omega:
  kind: "uniform"
  low: -1.0
  high: 1.0

sim:
  dt: 0.01
  T: 5.0
  burn_in: 2.0
  R_target: 0.95
  method: "RK45"
  n_trajectories: 3

# MPNN Surrogate parameters (Stage 1 data)
surrogate:
  hidden: 128
  dropout: 0.1
  mocu_scale: 1.0
  
  # Stage 1: Large dataset for surrogate training (MOCU only)
  n_train: 2000          # Surrogate training samples
  n_val: 400             # Surrogate validation samples
  n_theta_samples: 30    # MC samples for MOCU computation
  
  # Training parameters
  epochs: 100
  lr: 0.001
  batch_size: 512
  
  # Stage 2: ERM computation parameters (for DAD data)
  n_erm_samples: 10      # MC samples for ERM computation
  max_erm_candidates: 10 # Max candidates to compute ERM for

# DAD Policy parameters (Stage 2 data)
dad_rl:
  hidden: 128
  epochs: 30
  episodes_per_epoch: 50
  lr: 0.0002
  
  # Stage 2: Smaller dataset for DAD training (MOCU + ERM)
  n_train: 500           # DAD training samples (1/4 of surrogate)
  n_val: 100             # DAD validation samples (1/4 of surrogate)

enable_dad: true

advanced:
  bisection:
    tol: 0.001
    max_expand: 20
    max_iter: 40
    verbose: false
  data_gen:
    parallel: false
    cache_labels: true
    two_stage: true        # Enable two-stage generation
  eval:
    save_trajectories: false
    compute_diagnostics: true
