# Updated configs/config.yaml with paper-matched parameters

N: 5
K: 4
seed: 42

# Use adaptive bounds like the paper (will be computed per instance)
# These are fallback values only
prior_lower: 0.05
prior_upper: 0.50

omega:
  kind: "uniform"
  low: -3.0    # Increased range to match paper
  high: 3.0

sim:
  dt: 0.00625   # 1/160 to match paper exactly
  T: 5.0
  burn_in: 2.0
  R_target: 0.95
  method: "RK45"
  n_trajectories: 3

# MPNN Surrogate parameters (Stage 1 data)
surrogate:
  hidden: 128
  dropout: 0.1
  mocu_scale: 1.0
  
  # CRITICAL: Increased MC samples to match paper's approach
  n_train: 2000
  n_val: 400
  n_theta_samples: 1000    # Increased from 30 to 1000 (paper uses 20480 but 1000 is reasonable)
  
  # Training parameters
  epochs: 100
  lr: 0.001
  batch_size: 512
  
  # Stage 2: ERM computation parameters
  n_erm_samples: 10
  max_erm_candidates: 10

# DAD Policy parameters (Stage 2 data)
dad_rl:
  hidden: 128
  epochs: 30
  episodes_per_epoch: 50
  lr: 0.0002
  
  n_train: 500
  n_val: 100

enable_dad: true

advanced:
  bisection:
    tol: 0.001
    max_expand: 20
    max_iter: 40
    verbose: false
  data_gen:
    parallel: false
    cache_labels: true
    two_stage: true
    use_adaptive_bounds: true  # NEW: Enable adaptive bounds like paper
  eval:
    save_trajectories: false
    compute_diagnostics: true