# Updated configs/config_fast.yaml
# Fast Configuration for Quick Testing with Two-Stage Generation

N: 5
K: 4
seed: 42

prior_lower: 0.05
prior_upper: 0.50

omega:
  kind: "uniform"
  low: -1.0
  high: 1.0

sim:
  dt: 0.01
  T: 3.0              # Reduced from 5.0
  burn_in: 1.0        # Reduced from 2.0
  R_target: 0.95
  method: "RK45"
  n_trajectories: 2   # Reduced from 3

# MPNN Surrogate parameters (Stage 1 data)
surrogate:
  hidden: 128
  dropout: 0.1
  mocu_scale: 1.0
  
  # Stage 1: Smaller dataset for fast testing
  n_train: 500          # Reduced from 2000
  n_val: 100            # Reduced from 400
  n_theta_samples: 10   # Reduced from 30 (BIGGEST SPEEDUP)
  
  # Training parameters
  epochs: 50            # Reduced from 100
  lr: 0.001
  batch_size: 512
  
  # Stage 2: ERM computation parameters
  n_erm_samples: 5      # Reduced from 10
  max_erm_candidates: 8 # Reduced from 10

# DAD Policy parameters (Stage 2 data)
dad_rl:
  hidden: 128
  epochs: 20            # Reduced
  episodes_per_epoch: 30
  lr: 0.0003
  
  # Stage 2: Even smaller dataset for fast testing
  n_train: 100          # Small for testing
  n_val: 20             # Small for testing

enable_dad: true

advanced:
  bisection:
    tol: 0.002        # Relaxed from 0.001
    max_expand: 15    # Reduced from 20
    max_iter: 30      # Reduced from 40
    verbose: false
  data_gen:
    parallel: false
    cache_labels: true
    two_stage: true    # Enable two-stage generation
  eval:
    save_trajectories: false
    compute_diagnostics: true