# RTX 4090 Optimized Configuration
# Expected runtime: ~8 minutes for full pipeline

N: 5                    # Number of oscillators
K: 4                    # Number of experiments
seed: 42

prior_lower: 0.05
prior_upper: 0.50

omega:
  kind: "uniform"
  low: -1.0
  high: 1.0

sim:
  dt: 0.01
  T: 5.0
  burn_in: 2.0
  R_target: 0.95
  method: "RK45"
  n_trajectories: 3

surrogate:
  hidden: 128
  dropout: 0.1
  mocu_scale: 1.0
  n_train: 2000
  n_val: 400
  n_theta_samples: 30
  epochs: 100
  lr: 0.001
  batch_size: 512

dad_rl:
  hidden: 128
  epochs: 30           # Even more for full config
  episodes_per_epoch: 50
  lr: 0.0002     # Changed from 0.001

enable_dad: true

advanced:
  bisection:
    tol: 0.001
    max_expand: 20
    max_iter: 40
    verbose: false
  data_gen:
    parallel: false
    cache_labels: true
  eval:
    save_trajectories: false
    compute_diagnostics: true