# Configuration for Kuramoto Experiment Design (Fixed K)
# Updated with better parameters for the corrected implementation

# System parameters
N: 5                    # Number of oscillators
K: 4                    # Number of experiments to run (fixed budget)
seed: 42                # Random seed for reproducibility

# Prior belief intervals for coupling strengths
prior_lower: 0.05       # Lower bound of prior interval
prior_upper: 0.50       # Upper bound of prior interval

# Simulation parameters for Kuramoto + pacemaker dynamics
sim:
  dt: 0.01              # Time step for output (integration uses adaptive stepping)
  T: 5.0                # Total simulation time
  burn_in: 2.0          # Time to discard for transient behavior
  R_target: 0.95        # Synchronization threshold (order parameter)
  method: "RK45"        # Integration method: RK45 (adaptive) or Euler
  n_trajectories: 3     # Number of trajectories to average over

# Natural frequency distribution
omega:
  kind: "uniform"       # Distribution type: uniform or normal
  low: -1.0             # Lower bound (for uniform)
  high: 1.0             # Upper bound (for uniform)

# Surrogate model training parameters
surrogate:
  mocu_scale: 1.0       # Scaling factor for MOCU predictions
  erm_noise: 0.00       # Noise level for ERM (not currently used)
  hidden: 64            # Hidden dimension for neural networks
  dropout: 0.1          # Dropout rate
  
  # Training data generation
  n_train: 200          # Number of training samples (reduced for demo; use 1000+ for production)
  n_val: 50             # Number of validation samples
  n_theta_samples: 10   # MC samples for MOCU/ERM estimation (20+ recommended for production)
  
  # Training hyperparameters
  epochs: 30            # Training epochs (50+ for production)
  lr: 0.001             # Learning rate
  batch_size: 512

# DAD (Deep Adaptive Design) policy parameters
dad_bc:
  hidden: 64            # Hidden dimension for policy network
  epochs: 3             # Behavior cloning epochs
  episodes_per_epoch: 20 # Episodes per epoch
  lr: 0.001             # Learning rate

# Feature flags
enable_dad: true        # Whether to train and evaluate DAD policy

# Advanced options (for fine-tuning)
advanced:
  # Bisection search parameters for finding optimal a_ctrl
  bisection:
    tol: 0.001          # Tolerance for convergence
    max_expand: 20      # Maximum expansion iterations
    max_iter: 40        # Maximum bisection iterations
    verbose: false      # Print debug information
  
  # Data generation options
  data_gen:
    parallel: false     # Use parallel processing (not implemented yet)
    cache_labels: true  # Cache expensive label computations
  
  # Evaluation options
  eval:
    save_trajectories: false  # Save full ODE trajectories
    compute_diagnostics: true  # Compute detailed synchronization metrics