N: 5
K: 4
seed: 42

prior_lower: 0.05
prior_upper: 0.50

sim:
  dt: 0.01
  T: 5.0
  burn_in: 2.0
  R_target: 0.95

omega:
  kind: "uniform"
  low: -1.0
  high: 1.0

surrogate:
  mocu_scale: 1.0
  erm_noise: 0.00
  n_train: 1000
  n_val: 200
  epochs: 50

dad_bc:
  epochs: 3
  episodes_per_epoch: 30
  lr: 1e-3

enable_dad: true
